### ISSUE TITLE
wasm deterministic builds

### ISSUE THREAD

**Issue by tzemanovic** [anomanetwork/anoma#154]
With @sribst, we noticed some difference between wasm built on mac vs. Arch linux. We need to ensure that the wasm builds are deterministic (especially for transactions and VPs).

One reason could be different rust version, so we should lock the project to specific version in the `rust-toolchain` file. There has also been a bug in LLVM described in detail in https://dev.to/gnunicorn/hunting-down-a-non-determinism-bug-in-our-rust-wasm-build-4fk1, but that should have already been fixed. We could use a similar technique describe in the blog to check for deterministic build in the CI (compare hash of two build outputs: https://github.com/paritytech/substrate/pull/6597/files).

**Comment by yito88** [comment]
I tried building on docker with #255. The paths depending on the machine(docker container) are included in wasm.
However, they look constant if we use the docker image.

rust:
`/usr/local/rust/project/shared/src/types/address.rs`

cargo:
`/usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/bech32-0.8.0/src/lib.rs`

rustc:
`/rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/core/src/fmt/mod.rs`

rustup:
`/usr/local/rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/alloc/src/string.rs`

**Comment by tzemanovic** [comment]
thank you, @yito88 ! I'm adding the built wasm back to git in #272
