### ISSUE TITLE
ledger genesis initialization

### ISSUE THREAD

**Issue by tzemanovic** [anomanetwork/anoma#230]
The genesis initialization is currently performed in `Shell::new`, but it should only happen in `Shell::init_chain`

**Comment by batconjurer** [comment]
There are several functions a `Shell` can *theoretically* run on an uninitialized chain, but it is not clear if we *should* allow it. For example, `mempool_validate` or `begin_block`.

**Comment by tzemanovic** [comment]
> There are several functions a `Shell` can _theoretically_ run on an uninitialized chain, but it is not clear if we _should_ allow it. For example, `mempool_validate` or `begin_block`.

I don't think we need to worry about that for now as the initialization is specified and handled by Tendermint ABCI. The handshake first invokes `GetInfo` request and if no previous state it will issue `InitChain`. We could potentially check that we're on the expected block height in `begin_block`, but there's no danger in `mempool_validate`.

**Comment by batconjurer** [comment]
Clear, that makes this much simpler.

**Comment by tzemanovic** [comment]
done in #319
