### ISSUE TITLE
tendermint `DeliverTx.code=1` issue

### ISSUE THREAD

**Issue by tzemanovic** [anomanetwork/anoma#236]
We've noticed this issue in the playnet.

There were 4 validator nodes running on cloud (ubuntu). Once I connected to them with a local non-validator node (on mac - not sure if that's relevant), any transaction that was invalid (we set `code=1` in ABCI deliverTx response) wasn't getting evicted from my local node's mempool and so it kept gossiping it after it was applied in a block and the transaction was getting indefinitely applied in all following blocks. This would happen no matter to which RPC the transaction was originally submitted to.

I was able to replicate this again on a fresh state in the same setup, but I'm not able to replicate with a local-only network with validator nodes and a non-validator node.

As a workaround for playnet, we've commented out the code that sets `code=1`. I will try to debug this further once we're done with playnet.

**Comment by marbar3778** [comment]
Does your code implement replay protection? On top of this there are a couple issues in Tendermint that overlap with this

**Comment by marbar3778** [comment]
Does your code implement replay protection? On top of this there are a couple issues in Tendermint that overlap with this

**Comment by tzemanovic** [comment]
> Does your code implement replay protection? On top of this there are a couple issues in Tendermint that overlap with this

Thanks for commenting on this! We don't do replay protection yet. By any chance, do you know what the issues are? I tried to look, but couldn't find anything relevant.

**Comment by marbar3778** [comment]
here are two:
- https://github.com/tendermint/tendermint/issues/5281
- https://github.com/tendermint/tendermint/issues/3865

If you don't have replay protection you most likely have the second issue (3865)

**Comment by tzemanovic** [comment]
> here are two:
> 
>     * [tendermint/tendermint#5281](https://github.com/tendermint/tendermint/issues/5281)
> 
>     * [tendermint/tendermint#3865](https://github.com/tendermint/tendermint/issues/3865)
> 
> 
> If you don't have replay protection you most likely have the second issue (3865)

Thank you! It's odd, because in our case the load was very low. I'll try to look into this a bit further soon

**Comment by tzemanovic** [comment]
I looked into this a bit further. As I wasn't familiar enough with the all config options in tendermint, I missed that the `keep-invalid-txs-in-cache` is set to `false` by default. In a local network (or with small network delay), the invalid tx wasn't getting re-applied, presumably because they all removed the tx from their local mempool in synchrony, but once there was a node with bigger network delay, the invalid transaction kept getting re-applied indefinitely

**Comment by tzemanovic** [comment]
> I looked into this a bit further. As I wasn't familiar enough with the all config options in tendermint, I missed that the `keep-invalid-txs-in-cache` is set to `false` by default. In a local network (or with small network delay), the invalid tx wasn't getting re-applied, presumably because they all removed the tx from their local mempool in synchrony, but once there was a node with bigger network delay, the invalid transaction kept getting re-applied indefinitely

Anyway, I think in our case, we'll want to set `keep-invalid-txs-in-cache = true`.
