### ISSUE TITLE
chain ID in storage

### ISSUE THREAD

**Issue by tzemanovic** [anomanetwork/anoma#268]
We should write the DB into a subdir (has a `TODO` in code in `ledger::Storage::commit()`) and update the loading of state. The chain ID has to be known before we try to load the state. We should set the chain ID in `genesis` module and override the one in tendermint with it (like we do with the validator for "dev" feature with `write_validator_key`).

Also, we shouldn't return this from `DB::read_last_block` in the `BlockState`. Furthermore, we should write the `BlockState` type in `DB::write_block`.

Perhaps we can also load the state from storage earlier, before we receive `GetInfo` from ABCI as we currently do, so if there's a problem with storage, we don't even start-up a tendermint node.

**Comment by yito88** [comment]
@tzemanovic 
> We should write the DB into a subdir

Do you mean that we add a prefix `<chain_id>/` to the DB key? I'm not sure about "subdir".

**Comment by tzemanovic** [comment]
> @tzemanovic
> 
> > We should write the DB into a subdir
> 
> Do you mean that we add a prefix `<chain_id>/` to the DB key? I'm not sure about "subdir".

We currently store the DB files under `.anoma/db` (with the default `--base-dir .anoma`) taken from `config::Ledger::db` field. I think we should store it under `.anoma/db/{chain_id}` to avoid conflicts with fractal scaling instances and/or protocol upgrade instances.

Furthermore, we currently use a chain ID generated by Tendermint node, but we can provide our own instead. We could add a field to `genesis::Genesis`, for now it can simply be a string (it has to match the `CHAIN_ID_LENGTH = 20` we have set, or we can update the constant). For development, we can set it to e.g. `"anoma-devchain-00000"`.

Then we can write the chain ID into `.anoma/tendermint/config/genesis.json` (using https://docs.rs/tendermint/0.19.0/tendermint/genesis/struct.Genesis.html). This can be done before or after the call to `update_tendermint_config`.

Once we have that, when we receive the `InitChain` msg from ABCI, we should check that the chain ID in the request is matching our genesis chain ID.
